### ISSUE TITLE
学位论文扉页格式

### ISSUE THREAD

**Issue by seven-share** [sigmarising/BUPTMasterThesisWord#1]
https://webvpn.bupt.edu.cn/https/77726476706e69737468656265737421f7e552d225257844300d8db9d6562d/content/content.php?p=5_40_725

这是官网的论文扉页，我下载了您的模板，感觉扉页样子有出入，不知道是不是我word版本的问题，您再看看？

**Comment by sigmarising** [comment]
@seven-share 

本 Word 模板的扉页是基于研究生院提供的扉页模板制作的，并进行了如下修改：
* 替换研究生院扉页的低清晰度图片为高清晰度
* 鉴于研究生院提供的模板横线栏过短，无法放下过长的题目、专业名、学院名（如SCS），所以对横线栏目均使用了制表位和右缩进调整了长度和对齐
* 研究生院未提供英文扉页，故基于中文扉页样式自制了英文扉页

对于所有的横线栏目可以自行删除或者调整长度以适应需求。

当然，如果还是更倾向于官方提供的原版模板，只需替换扉页部分（Ctrl C V，注意样式匹配）即可。

**Comment by sigmarising** [comment]
Close by Release [v1.2.0](https://github.com/sigmarising/BUPTMasterThesisWord/releases/tag/v1.2.0)
