### ISSUE TITLE
[bug] 2017 要求中，图编号要求为全部为阿拉伯数字，目前模板中为汉字-数字

### ISSUE THREAD

**Issue by SwordFaith** [sigmarising/BUPTMasterThesisWord#2]
![image](https://user-images.githubusercontent.com/18397468/159264626-b75ac15f-9746-4ce3-8626-d420bfa72ea4.png)

**Comment by sigmarising** [comment]
### 摘自模板使用说明 2.8 节

> 由于Word并未提供题注的正规编码功能 ，所以自动生成的题注（图片、表格、公式） 会生成“二 -1”而非 2-1”的形式。 本文将给出两种解决方法来解决这个问题。
>
> 第一种方法，手动敲入题注内容，并套用“题注”样式。这种方法需要手工编号，并且无法使用 Word的交叉引用功能。
>
> 第二种方法，暂时无视这个问题，在需要进行文档输出时，进行一次域代码相关的操作（详细内容参见 第四章 ）。

![Usage 2.8](https://user-images.githubusercontent.com/25470568/159270614-0aea1aad-a0ef-449a-bfaa-c970c71e7eda.png)

---

### 按照 issue 标题描述，推测使用了交叉引用，请参考模板使用说明第四章的内容进行题注修复

![修复题注](https://user-images.githubusercontent.com/25470568/159271152-667d25d6-c600-42e0-8f0b-567d614bc6df.png)
