### ISSUE TITLE
题注错误

### ISSUE THREAD

**Issue by ZhengtianZhu** [sigmarising/BUPTMasterThesisWord#3]
1.因为模板使用了自有的样式：北邮论文标题一、二、三，导致 usage2.9节图片插入题注，实际是无法链接到文章的，因此，
我建议是：对标题一、二、三直接修改样式，这样才能用上usage 图片题注的方法
希望楼主能采纳

2.一个疑问：大家引用文章都是一个个网站点击cite的吗？？还是endnote引用加入？二者只能选其一吗？？
我都被这2个混合使用给搞死了。

**Comment by ZhengtianZhu** [comment]
3.可以设置正文段落的首行缩进，
4. 还是叠加1，因为每次找“北邮论文标题一”的样式，确实有点麻烦，1）要打开样式显示所有，2）或者格式刷之类的，会有点抓狂
5. 其他同学使用小tip，直接题注设定 图1- , 图2-，这样自动编号，就不用用usage里的解释代码大法了。不过大家一定都有办法解决这个图排序问题。
挺可惜的，现在大学没有专门做模板，结果让同学们不能专注内容本身，还得被繁琐的格式折腾，果然效率降低。

**Comment by sigmarising** [comment]
Sorry for the late reply @ZhengtianZhu .

1. 如果我没记错的话，我是直接对“标题1，标题2，……”的样式进行的修改
  并未创建自有样式“北邮论文标题1，北邮论文标题2，……”
  至少我刚刚下载模板后验证了是如此的。所以我也并未了解清楚无法链接到文章是什么情况，可能需要提供更多信息
  ![image](https://user-images.githubusercontent.com/25470568/189785630-99c9897d-40a6-45ee-96a0-6f02ca1f1e6a.png)
2. 我在编写毕业论文时，引用文章是采用了手动编排的格式
  Reason 1：我从来没用过 Endnote 等软件，也不会用😂
  Reason 2：所有的已有参考文献规则格式要求都或多或少不符合《标准》要求，所以我都是采用手动编排的
  我个人也强烈不建议混合使用多种文献管理工具。如果你有兴趣研究这个的话，欢迎提出改进方法😂
3. 由于“正文”样式是作为“基准”的存在，影响了太多其他的样式，所以直接给“正文”样式设定缩进不是一个好主意。
  作为代替的，我在模板中提供了一个“正文-缩进”的独立样式，不仅可以独立使用，而且它也作为所有标题后新行的样式
  而且我尽可能将这个样式排到了样式库第二位，使用起来应该不是特别麻烦。
4. 我从未创建过“北邮论文标题一”的样式，希望提供更多信息
5. 我没太看懂…………希望对此提供更多信息
  题注设定“图X“是否意味着提前占位所有题注编号？（例如从图1到图30？）
  就我个人的场景而言，我动辄一个章节引用图片达60多张，这显然是很不现实的工作量😂

Best.

**Comment by sigmarising** [comment]
@ZhengtianZhu 

Gently ping this thread.\
If there is no more update of this issue, I'll close it in a week.

Thanks.

**Comment by sigmarising** [comment]
Close this issue since there is no more information provided.
