### ISSUE TITLE
如何将改动更新到我的word里

### ISSUE THREAD

**Issue by super233** [sigmarising/BUPTMasterThesisWord#5]
我已经基于之前的版本写很多了，论文里有太多的图、表、公式和交叉引用，但是后面更新的版本又解决了若干bug，如果要使用新版的话复制粘贴不太可能，请问有什么方法可以将您的改动更新到我目前的word里吗？

最后，感谢大佬的无私开源~ 😄

**Comment by sigmarising** [comment]
@super233 请问同学你使用的是哪个版本（具体版本号）的模板？

模板自 v1.2.0 之后样式库是未修改过的，后续的一些更改是关于分节符编排的，并不困难，我可以在这个 thread 里把修改的步骤详细列一下

**Comment by super233** [comment]
我使用的版本是 v2.0.0，辛苦大佬说明下修改步骤 👍

**Comment by sigmarising** [comment]
Hi @super233 

v2.0.0 版本到 v2.0.4 版本的改动如下：
1. v2.0.0 版本的第三章末尾的分节符为“分节符”而非“分节符（奇数页）”，首先的更改即将这个“分节符”删除，替换为“分节符（奇数页）”（如何插入分节符请参考[官方文档](https://support.microsoft.com/zh-cn/office/%E6%8F%92%E5%85%A5%E5%88%86%E8%8A%82%E7%AC%A6-eef20fd8-e38c-4ba6-a027-e503bdf8375c)）
2. 然后可能会遇到一个奇怪的问题，当第三章末尾的“分节符”替换为“分节符（奇数页）”后，\
  原本第二章末尾的“分节符（奇数页）”会变成普通的“分节符”，\
  所以对第二章末尾分节符进行同样的操作
4. 然后第一章末尾的分节符也会变………………\
  继续如上的替换
6. 然后有很大概率第一章的页码起始页会出现问题，直接让第一章的页码重新从1开始计数即可

上述的 2~4 的问题也是我做完修改后才发现的，所以在一晚上连续发了四个修复版本😂

**Comment by super233** [comment]
好的，感谢回复~
