### ISSUE TITLE
“关于调整研究生学位论文封面与扉页格式、增设答辩委员会名单页的通知”

### ISSUE THREAD

**Issue by super233** [sigmarising/BUPTMasterThesisWord#6]
学校调整了一下模板，3月17号的通知。
http://my.bupt.edu.cn/content.jsp?urltype=news.NewsContentUrl&wbtreeid=1626&wbnewsid=105307

**Comment by sigmarising** [comment]
是的，两周前我其实已经看到了，教务又要达成他们的 5 年 KPI 了，但依旧不提供官方模板（乐）

我这边的更新是肯定要安排的，不过最近比较忙，等闲下来了会更新 V3 版本。

感谢你的支持！

**Comment by sigmarising** [comment]
祝毕业快乐

close this issue by [PR7](https://github.com/sigmarising/BUPTMasterThesisWord/pull/7)
